appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: pDpcXDkr4E5mgV3b4h98NrqzBxpBuSFmZYD0imgIrEphHRNhdPcMkZcOT0g2hsMcFM83osBN/q4QH0J7bqIMan93xSz1+WlXt4oddP51ZBNhmCTr8lUFc1DQCFnRYVyvpOHh1mhuNg3iqsExUBlZjon9U8CxutBEs1kElydqqsGU+9J3DWjlN7BnA01yAsZRnjNPbkUx9BGZNbFRgNxDLg/c929nXN/is1MEhna7jb94zFSVfF1CzDb4zkfhnZ5JeFDUzwfY1gM7qtKKJAKJwCEbRhiYSoeGJ1oi/H7cwV7B1aLtCyek78EeSKCF1AvLOpFsZNh0WuyOfymnbjsmZmRNubOkViypmsEWsmyAq0YesaVoJ4sVag13q/dPqfNpnwIxxbjL6bhX2KTOJ9i0qe+wOSg0QMw7Of5R55BiQg3Q64QN0v6NN5iv6HOBvc7m32NKbAyAJK70gjxsSzxzBcVjvubo1SgeqxFIS4zBU3rAtLr94UBlZzzgjZMrNBoMiUmLh4ZtvDcsMmZpgrul1souBcHxFVEUmNRZVOtfeY37YGeSyWX0pffvJkMKyeztohuwj3C4e7wn1cSd5mzFIxD4lrgrwwt6NwUxzk+lWkd7cT+CyUeq4lRW2eSG+m8bhOwebFjNGghOoAuk2pYVq/VObbG9fZ6KiCd9amkUy+s=
conda_forge_output_validation: true
